package com.borrow.blockchain.entity;
// Generated 27-Mar-2018 10:58:38 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PropertyConfig generated by hbm2java
 */
@Entity
@Table(name = "PROPERTY_CONFIG", schema = "DRAWING_ROOM")
public class PropertyConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String prcfConfigKey;
	private String prcfConfigVal;
	private char prcfConfigStatus;
	private String prcfConfigDesc;
	private Date prcfCreatDtm;
	private String prcfCreatBy;

	public PropertyConfig() {
	}

	public PropertyConfig(String prcfConfigKey, String prcfConfigVal, char prcfConfigStatus, Date prcfCreatDtm,
			String prcfCreatBy) {
		this.prcfConfigKey = prcfConfigKey;
		this.prcfConfigVal = prcfConfigVal;
		this.prcfConfigStatus = prcfConfigStatus;
		this.prcfCreatDtm = prcfCreatDtm;
		this.prcfCreatBy = prcfCreatBy;
	}

	public PropertyConfig(String prcfConfigKey, String prcfConfigVal, char prcfConfigStatus, String prcfConfigDesc,
			Date prcfCreatDtm, String prcfCreatBy) {
		this.prcfConfigKey = prcfConfigKey;
		this.prcfConfigVal = prcfConfigVal;
		this.prcfConfigStatus = prcfConfigStatus;
		this.prcfConfigDesc = prcfConfigDesc;
		this.prcfCreatDtm = prcfCreatDtm;
		this.prcfCreatBy = prcfCreatBy;
	}

	@Id

	@Column(name = "PRCF_CONFIG_KEY", unique = true, nullable = false, length = 100)
	public String getPrcfConfigKey() {
		return this.prcfConfigKey;
	}

	public void setPrcfConfigKey(String prcfConfigKey) {
		this.prcfConfigKey = prcfConfigKey;
	}

	@Column(name = "PRCF_CONFIG_VAL", nullable = false, length = 2000)
	public String getPrcfConfigVal() {
		return this.prcfConfigVal;
	}

	public void setPrcfConfigVal(String prcfConfigVal) {
		this.prcfConfigVal = prcfConfigVal;
	}

	@Column(name = "PRCF_CONFIG_STATUS", nullable = false, length = 1)
	public char getPrcfConfigStatus() {
		return this.prcfConfigStatus;
	}

	public void setPrcfConfigStatus(char prcfConfigStatus) {
		this.prcfConfigStatus = prcfConfigStatus;
	}

	@Column(name = "PRCF_CONFIG_DESC", length = 100)
	public String getPrcfConfigDesc() {
		return this.prcfConfigDesc;
	}

	public void setPrcfConfigDesc(String prcfConfigDesc) {
		this.prcfConfigDesc = prcfConfigDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRCF_CREAT_DTM", nullable = false, length = 26)
	public Date getPrcfCreatDtm() {
		return this.prcfCreatDtm;
	}

	public void setPrcfCreatDtm(Date prcfCreatDtm) {
		this.prcfCreatDtm = prcfCreatDtm;
	}

	@Column(name = "PRCF_CREAT_BY", nullable = false, length = 30)
	public String getPrcfCreatBy() {
		return this.prcfCreatBy;
	}

	public void setPrcfCreatBy(String prcfCreatBy) {
		this.prcfCreatBy = prcfCreatBy;
	}

	@Override
	public String toString() {
		return "PropertyConfig [prcfConfigKey=" + prcfConfigKey + ", prcfConfigVal=" + prcfConfigVal
				+ ", prcfConfigStatus=" + prcfConfigStatus + ", prcfConfigDesc=" + prcfConfigDesc + ", prcfCreatDtm="
				+ prcfCreatDtm + ", prcfCreatBy=" + prcfCreatBy + "]";
	}

}
